### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by jomei** [jeizsm/test-project#1]
Привет!
1. если ты заводишь какой то кастомный способ старта твоего приложения(`app.sh`), то следует указать это в документации
2. Отстутсвует возможность конфигурировать подключение к redis
3. Если при старте приложение не смогло подключиться к redis, оно просто молча зависает

Пингани меня в этой issue, после того как исправления будут внесены.

**Comment by jeizsm** [comment]
@jomei сделал
